### ISSUE TITLE
Typo in save_to_huggingface.py script?

### ISSUE THREAD

**Issue by vgaraujov** [kb-labb/kb_bart#2]
Hello!

Nice repo. I was checking your `save_to_huggingface.py` script and noticed that you assign </s> as the cls token when loading the tokenizer. Should not be <s>?

https://github.com/kb-labb/kb_bart/blob/0ebef760495962f32e3885087db197f496416185/save_to_huggingface.py#L44

**Comment by Lauler** [comment]
Yes, I think you are right. That seems to be a mistake. 

Thanks for pointing it out, will fix. 

https://github.com/kb-labb/kb_bart/commit/696acb13bc25d314bea814625ff5897ed8c725d0
